services:
  - name: server
    buildCommand: docker-compose build server
    startCommand: docker-compose up server
    healthCheckPath: /health
  - name: postgredb
    buildCommand: docker-compose build postgredb
    startCommand: docker-compose up postgredb
    healthCheckPath: /health
volumes:
  - name: postgredb-data
