services:
  - type: server
    name: server
    buildCommand: docker-compose build server
    startCommand: docker-compose up server
    healthCheckPath: /health
    environment:
      - PORT=${PORT}
  - type: database
    name: postgredb
    buildCommand: docker-compose build postgredb
    startCommand: docker-compose up postgredb
    healthCheckPath: /health
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HOSTNAME=${DB_HOSTNAME}
      - PORT=${DB_PORT}
      - DATABASE=${DATABASE}

volumes:
  - name: postgredb-data
